os: osx
sudo: required
#启用chrome
addons:
  chrome: stable
language: node_js
node_js:
  - "6.0.0"
script: "npm run build && npm run build-demo"
after_success:
  - bash <(curl -s https://codecov.io/bash)
