language: node_js
node_js:
  - "6.0.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "npm run build && npm run build-demo && npm run test"
after_script: "npm install coveralls@3.0.0 && cat ./coverage/lcov.info | coveralls"
